
### url参数
GET  http://127.0.0.1:5000/test?hello=123 HTTP/1.1

### post
PUT  http://127.0.0.1:5000/test
Content-Type: application/json

{
    "price":123
}


### testTheUser API query
GET http://localhost:5000/admin/users/ HTTP/1.1

### testTheUser API add
POST http://localhost:5000/admin/users/ HTTP/1.1
Content-Type: "application/x-www-form-urlencoded"

id:123
&username:"test"
&nickname:"test"
&city:"shenzhen"
&iphone:"1231564"


